### ISSUE TITLE
DLQ in KPL

### ISSUE THREAD

**Issue by ChengzhiZhao** [awslabs/amazon-kinesis-producer#265]
I was wondering if there is DLQ when a message expires, or what's the suggested way to handle a potential dropped message if message not able to deliver within TTL. Thanks!

**Comment by Cory-Bradshaw** [comment]
KPL does not support DeadLetterQueues, but when a record is not written to a stream due to an expired TTL, the async Function returned by the addUserRecord() call will contain the error and a reference to the data it was unable to deliver.  By handling these failures in the Future returned you can then move them into a DLQ as you desire.
