### ISSUE TITLE
Unexpected peformance

### ISSUE THREAD

**Issue by rdifalco** [awslabs/amazon-kinesis-producer#43]
I'm seeing fewer puts per second than I would expect. I have a 25 shard stream and to stream producers running on m4.xlarge instances. When one instance is running I get about 25K `#addUserRecord` calls per second with aggregation enabled. Before KPL I would get about 25K puts per second with about 25M bytes per second throughput. 

With KPL I *still* get 25M bytes per second throughput but I only get about 200 puts per second throughput. I guess I expected this to be a lot higher with aggregation. I figured I'd get >25K puts per second instead of only ~200-300 puts per second. 

Is this a documentation error, for example, can I not go any higher than 25M bytes per second with 25 shards?

**Comment by samuelgmartinez** [comment]
Where are you getting the measures about the put request/sec ratio?
If you are reading that info in the kinesis metrics dashboard, what you are reading is the aggregated puts, each record contains a lot of aggregated records inside (that's what aggregation in KPL means: adding "virtual" records to a single record), and that's the reason why you are seeing the same data transfer performance, because you are sending the same amount of data but "compressed" in fewer puts.
