### ISSUE TITLE
Disk-based persistence

### ISSUE THREAD

**Issue by jakajancar** [awslabs/amazon-kinesis-producer#62]
Hi,

We're designing a system that will pump data to Kinesis and are concerned about temporary unavailability of the Kinesis service, going over capacity for let's say an hour, or failures of individual shards or network connections to them.

If I understand correctly, Kinesis Producer Library buffers everything in memory. This gives us a very very small buffer (time wise) as we will quickly run out of memory.

We're thinking of building a buffer in front of KPL, but it seems more efficient for this to be done inside the KPL, ideally somewhere between the reducer and the limiter, so at the shard level.

Has this been considered yet? How do most people handle this? Just pass to KPL, let it buffer in memory and cross fingers?

Thanks,
 Jaka

//cc @apejcic

**Comment by samuelgmartinez** [comment]
Hey!

Here are my experience and thoughts about this kind of systems: it's all
about the back pressure.

For a disk buffering approach, if you have enough throughput, you will run
out of space eventually and you need a proper control for that particular
case and you will need a fail fast mechanism either way (and you'll lose
messages, of course)

So, in this case you will need to put a circuit breaker to fail fast (if
you are not in control of the message producing end, like if you generate
the message every time you receive a request in a REST endpoint) or a retry
mechanism if can control the pace you generate the messages.

We gather measures on how well the KPL is performing and we have alarms to
notice problems. Another thing to improve reliability is to put a retry
mechanism for every failed to deliver message.

Be careful about being throttled because, as you said, the kinesis daemon
buffers everything in memory, so if you keep sending events, you will run
out of memory. I think some people opened a bunch of issues about that
(using a circular buffer for the daemon, and daemon automatically restart
in case of failure)

Sorry for my crap writing, I know that isn't an excuse, but I'm on the
phone ;)

**Comment by pfifer** [comment]
I agree with Samuel on pretty much everything.  Disk based persistence doesn't guarantee the durability of actually storing it in Kinesis.  Additionally if you fall far enough behind you wouldn't necessarily have enough capacity to catch up.  The KPL would than constantly be running behind the actual tip, and always reading from disk.  

All of these increase the possibility of data loss. 

The current method of having the KPL trigger a future allows the application to provide a custom backoff, and further retry strategy.  It could be possible for the client application to persist messages that fail multiple times to disk for a different attempt system.

**Comment by kwinter** [comment]
Just to share how we handle this (we have a REST service sending a message on every request).  We put in our own backoff limit, which is checked against getOutstandingRecordsCount, and if it is above the threshold we skip the producer and log it to disk via slf4j (and a defensive size+time based rolling policy to prevent disk filling up under load), which is sucked up by AWS logs for recovery.  We can have large spikes in traffic, so popping our Kinesis limit and getting throttled is very likely, unless we over-provision shards and get the math right each time.  Holding a bunch of messages in memory was definitely a concern, so we ran a bunch of load tests against different backoff thresholds and our KPL settings to come up with a limit/memory usage we were comfortable with running under in our worst case

**Comment by pfifer** [comment]
@kwinter Thanks for the response that is a pretty good solution for handling spiky traffic.

I'm going to close this, please free to re-open if you have additional questions.
